### ISSUE TITLE
Consider deprecating?

### ISSUE THREAD

**Issue by ekryski** [Lughino/passport-unique-token#1]
In order to reduce confusion in npm, would you consider deprecating this lib in favour of https://github.com/leepowellcouk/passport-token?

**Comment by Lughino** [comment]
Because my module is different!
My need is to use only the token and not the username!

**Comment by ekryski** [comment]
@Lughino You can do that with his module :smile:. Here is a [link to the issue](https://github.com/leepowellcouk/passport-token/issues/9) where I describe how to do it.

I just put in a pull request for that functionality. Hopefully he merges it and it should make it easier.
