### ISSUE TITLE
Retrieve query fields directly from URL

### ISSUE THREAD

**Issue by HighSoftWare96** [Lughino/passport-unique-token#34]
I'm using this strategy for authenticating requests that possibly could not have the req.query filled. I was wondering if there a way to change this by retrieving the query fields directly parsing the URL instead of using req.query. I actually am stuck by this, in case I can make a PR.

**Comment by Lughino** [comment]
Hi there,

I’m not quite sure I understood what you want to achieve.
Is the token passed in the url as param? 
In that case, you can configure the `tokenParams` option.
E.g. your route is something like 
```javascript
app.get(‘/auth/token/:yourUniqueToken’, passport.authenticate('token'), (req, res) => {
// ....
})
```
and then you pass to the strategy the options `{ tokenParams: ‘yourUniqueToken’ }`
Is this solve your problem?

**Comment by HighSoftWare96** [comment]
I'm not using this with Express, so, for some reason, the field query in the req object isn't getting correctly filled. I've solved the issue by injecting all I required in the req object. I guess this is a too specific issue, I'm going to close this.
